# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Mantenha esta ou a versão que você tem
    hooks:
      # Mantenha SOMENTE os hooks que você quer que rodem.
      # Remova ou garanta que as linhas de hooks desabilitados estejam COMPLETAMENTE COMENTADAS
      # (incluindo o '-' inicial) ou removidas.
      - id: check-yaml
      - id: check-json
        exclude: \.pkl$|\.ipynb$ # Mantenha a exclusão
      # Não deve haver nenhum '-' solto ou linhas parcialmente comentadas aqui.

  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use a versão do seu pyproject.toml
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2 # Use a versão do seu pyproject.toml
    hooks:
      - id: isort
        name: isort (Python)
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0 # Use a versão do seu pyproject.toml
    hooks:
      - id: flake8