[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "attrition"
version = "0.1.0"
description = "Pipeline de ML para predição de rotatividade de funcionários"
authors = [
  { name="Mateus Cabral", email="mateuscsq@email.com" }
]
dependencies = [
  "pandas>=1.5",
  "numpy>=1.23",
  "scikit-learn>=1.2",
  "xgboost>=1.7",
  "imbalanced-learn>=0.10"
]

[project.scripts]
process-data      = "attrition.data.process:main"
engineer-features = "attrition.features.engineer:main"
train-model       = "attrition.models.train:main"