name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
      fail-fast: false

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar Poetry
        run: |
          pip install poetry

      - name: Configurar cache de dependências Poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Instalar dependências com Poetry
        run: |
          poetry install --no-root 

      - name: Executar lint (flake8)
        run: |
          poetry run flake8 src tests

      - name: Executar testes (pytest)
        run: |
          poetry run pytest --cov=src
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
          PYTHONPATH: ${{ github.workspace }}/src 

      - name: Executar testes (pytest)
        run: |
          echo "Debug: O tamanho da DATABASE_URL é: $(echo -n "$DATABASE_URL" | wc -c)"
          poetry run pytest --cov=src
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
          PYTHONPATH: ${{ github.workspace }}/src

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Disparar Deploy do Serviço Principal no Render
        run: |
          SERVICE_ID="srv-d1jdjcali9vc73ej98rg" 
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               "https://api.render.com/v1/services/${SERVICE_ID}/deploys"
          echo "✅ Deploy do serviço principal disparado para ${SERVICE_ID}"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}